### ISSUE TITLE
Loading models with Mountpoint for Amazon S3 is slow

### ISSUE THREAD

**Issue by walkley** [yubingjiaocn/stable-diffusion-webui-docker#1]
It takes **25s** to load model `v1-5-pruned-emaonly.safetensors` in **EFS**, similar result while enable/disable mmap in WebUI.

However, it takes **2 mins** to load same model from **S3** with the [Mountpoint for Amazon S3 CSI Driver](https://github.com/awslabs/mountpoint-s3-csi-driver/), with **mmap enabled** by default.

While **disabling mmap**, loading time dropped to **12s-15s,** even better than EFS.

**Comment by yubingjiaocn** [comment]
Closed since #2 is merged.
